#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Main application for the most gimli utility stuff"""


def main():
    """Entry function"""
    import argparse

    parser = argparse.ArgumentParser(description="sample application")

    # define some options (better import from defaultParser)
    parser.add_argument("-v", "--verbose", dest="verbose", action="store_true",
                        help="Be verbose")
    parser.add_argument("-i", "--integer", dest="integer", type=int,
                        help="Eine Integer Variable mit long und short option",
                        default=0)
    parser.add_argument("-s", dest="string", type=str,
                        help="Eine string Variable mit short option",
                        default='none')

    parser.add_argument('target')

    args = parser.parse_args()

    # results are in args
    if args.verbose:
        print(args)

if __name__ == "__main__":
    main()
