#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
pygi -- graphical interface to GIMLi
Copyright (C) 2009-2014 Carsten Rcker <carsten@resistivty.net>
Copyright (C) 2009-2014 Thomas Gnther <thomas@resistivty.net>

License - noch nicht entschieden -
"""

import sys


class WorkSpace:
    activeResource = None

    def __init__(self):
        None

if not hasattr(sys, "frozen"):
    # These checks are only necessary in a non-frozen environment, i.e., we
    # skip these checks when run from a py2exe-fied application
    try:
        import pygimli
    except ImportError:
        sys.stderr.write('''ERROR: cannot import the library 'pygimli'.''')
        sys.exit(1)


def start():
    from pygimli.gui import main

    global ws
    ws = WorkSpace()

    app = main.PyGIMLIApp(ws=ws)
    app.start()

if __name__ == '__main__':
    start()
