# -*- coding: utf-8 -*-
"""
Gimli documentation build configuration file.
#
# created by
# sphinx-quickstart on Wed Apr 11 16:37:21 2012.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.
"""

import math
import os
import re
import sys
from os import path
from os.path import join

import matplotlib
import pip
import pkg_resources
import sphinx

import pygimli as pg
from pygimli.utils import boxprint
from sidebar_gallery import make_gallery

# for doc rendering on headless machines (jenkins server)
matplotlib.use("Agg")

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
# sys.path.insert(0, os.path.abspath('.'))

try:
    # from _build.doc.conf_environment import *
    from conf_environment import *
except ImportError:
    TRUNK_PATH = '..'
    SPHINXDOC_PATH = '.'
    DOC_BUILD_DIR = ''
    DOXY_BUILD_DIR = ''
    boxprint("Building documentation in-source. Don't forget to make clean.")

sys.path.append(os.path.abspath(join(SPHINXDOC_PATH, '_sphinx-ext')))

# The following line is necessary for the Tools section
sys.path.append(os.path.abspath(join(TRUNK_PATH, 'python/apps')))

# -- General configuration ----------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
needs_sphinx = '1.2'

# Check for external sphinx extensions
deps = ['sphinxcontrib-programoutput', 'sphinxcontrib-bibtex', 'numpydoc']
modules = [str(m).rsplit()[0] for m in pip.get_installed_distributions()]

req = []
for dep in deps:
    if dep not in modules:
        req.append(dep)
if req:
    msg = "Sorry, there are missing dependencies to build the docs.\n" + \
          "Try: sudo pip install %s.\n" % (' '.join(req)) + \
          "Or install all dependencies with: pip install -r requirements.txt"
    raise ImportError(msg)

# Add any Sphinx extension module names here, as strings.
# They can be extensions coming with Sphinx (named 'sphinx.ext.*')
# or your custom ones.
extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.viewcode',
              'sphinx.ext.autosummary',
              'sphinx.ext.mathjax',
              'sphinx.ext.doctest',
              'sphinx.ext.intersphinx',
              'matplotlib.sphinxext.only_directives',
              'matplotlib.sphinxext.plot_directive',
              'myexec_directive',
              'myliterate_directive',
              'doxylink',
              'sphinx_gallery.gen_gallery', ]

extensions += [dep.replace('-', '.') for dep in deps]

# Sphinx-gallery settinga
try:
    import sphinx_gallery
    extensions += ["sphinx_gallery.gen_gallery"]

    # Setup automatic gallery generation
    sphinx_gallery_conf = {
        'examples_dirs': [join(SPHINXDOC_PATH, 'examples'),
                          join(SPHINXDOC_PATH, 'tutorials')],
        'gallery_dirs': ['_examples_auto', '_tutorials_auto'],
        'reference_url': {
            # The module you locally document uses a None
            'pygimli': None,
            # External python modules use their documentation websites
            'matplotlib': 'http://matplotlib.org',
            'numpy': 'http://docs.scipy.org/doc/numpy'
        },

        # path where to store your example linker templates
        'mod_example_dir': '_function_examples',

        # Your documented modules. You can use a string or a list of strings
        'doc_module': 'pygimli'
    }

except ImportError:
    err = """
    The sphinx_gallery extension is not installed, so the tutorials
    and examples will not be rendered and additional warnings will occur
    due to missing references.

    Install sphinx_gallery via:
    sudo pip install sphinx-gallery
    """

    def setup(app):
        app.warn(err)


intersphinx_mapping = {'http://docs.python.org/': None}

autoclass_content = "both"

# Get mathjax
# Formulas disappear after scrolling
# mathjax_path =
# "http://www.pygimli.org/mathjax/MathJax.js?config=TeX-AMS-MML_HTMLorMML"
# Slow, but works
mathjax_path = "https://cdn.mathjax.org/mathjax/latest/MathJax.js" +\
               "?config=TeX-AMS-MML_HTMLorMML"

# Add any paths that contain templates here, relative to this directory.
templates_path = [join(SPHINXDOC_PATH, '_templates'),
                  join(DOC_BUILD_DIR, '_templates')]

numpydoc_class_members_toctree = False
numpydoc_show_class_members = False
numpydoc_use_plots = True
plot_formats = [('png', 100), ('pdf', 100)]
plot_include_source = True

phi = (math.sqrt(5) + 1) / 2

plot_rcparams = {
    'font.size': 7,
    'axes.titlesize': 7,
    'axes.labelsize': 7,
    'xtick.labelsize': 7,
    'ytick.labelsize': 7,
    'legend.fontsize': 7,
    'text.usetex': False,
    'figure.subplot.bottom': 0.2,
    'figure.subplot.left': 0.2,
    'figure.subplot.right': 0.9,
    'figure.subplot.top': 0.85,
    'figure.subplot.wspace': 0.4,
    'figure.figsize': (3 * phi, 3),
    'figure.dpi': 100,
}

matplotlib.rcParams.update(plot_rcparams)

# The suffix of source filenames.
source_suffix = '.rst'

# The encoding of source files.
source_encoding = 'utf-8-sig'

# The master toctree document.
master_doc = 'documentation'

# General information about the project.
project = 'GIMLi'
copyright = '2016 - GIMLi Development Team'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = pg.__version__
# The full version, including alpha/beta/rc tags.
release = pg.__version__

release = release.replace('_', '\\_')

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
# language = None

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
# today_fmt = '%B %d, %Y'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = ['_build', '_sphinx-ext', '_templates', 'tmp', 'examples',
                    'tutorials', 'tutorial']

# The reST default role (used for this markup: `text`) to use for all documents
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'default'

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# -- Options for HTML output --------------------------------------------------

# Add any paths that contain custom themes here, relative to this directory.
html_theme_path = [join(SPHINXDOC_PATH, '_themes')]

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.

html_theme = 'gimli'

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
# html_theme_options = {}

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = "GIMLi - Geophysical Inversion and Modelling Library"

# A shorter title for the navigation bar.  Default is the same as html_title.
html_short_title = "GIMLi"

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = '_static/resisnet.png'

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
html_favicon = join(SPHINXDOC_PATH, '_static/favicon.ico')

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = [join(SPHINXDOC_PATH, '_static')]

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = '%b %d, %Y'  # + ' with ' + version

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
html_additional_pages = {'index': 'index.html', 'contact': 'contact.html'}

# If false, no module index is generated.
html_domain_indices = True

html_index = 'index.html'

# If false, no index is generated.
html_use_index = True

html_use_modindex = True

# If true, the index is split into individual pages for each letter.
html_split_index = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = True

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# does not have any affect. sphinx credit is located in footer.html
html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Output file base name for HTML help builder.
htmlhelp_basename = 'gimlidoc'

# -- Options for LaTeX output

# The name of an image file (relative to this directory) to place at the top of
# the title page.
latex_logo = join(SPHINXDOC_PATH, "_static/gimli_logo.pdf")

# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
# latex_use_parts = False

# If true, show page references after internal links.
latex_show_pagerefs = True

# If true, show URL addresses after external links.
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
# latex_domain_indices = True


extradir = path.abspath(join(SPHINXDOC_PATH, '_static'))  # .replace('\\', '/')

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    'papersize': 'a4paper',

    # The font size ('10pt', '11pt' or '12pt').
    'pointsize': '11pt',

    # Additional stuff for the LaTeX preamble.
    'preamble':
    '\\usepackage{amsfonts}\n\
    \\usepackage{amssymb}\n\
    \\usepackage{graphicx}\n\
    \\usepackage{amsmath}\n\
    \\usepackage{bm}\n\
    \\usepackage{pslatex}\n\
    \\graphicspath{{' + SPHINXDOC_PATH + '}}'
}

if sphinx.__version__.startswith('1.3'):
    latex_elements['preamble'] += \
        '\\RequirePackage{fixltx2e}\n\
     \\MakeRobust\\DUspan\n'

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual])
latex_documents = [('documentation', 'gimli.tex', 'GIMLi Documentation',
                    r'Carsten Rücker, Thomas Günther \& Florian Wagner',
                    'manual')]

try:
    pngmath_latex_preamble  # check whether this is already defined
except NameError:
    pngmath_latex_preamble = ""

pngmath_latex_preamble = '\
        \\usepackage{amsfonts}\n\
        \\usepackage{amssymb}\n\
        \\usepackage{amsmath}\n\
        \\usepackage{bm}\n\
        \\usepackage{pslatex}\n'

# latex.add_macro("\\newcommand{\\arr}[1]{\\ensuremath{\\textbf{#1}}}")

_mathpng_tempdir = DOC_BUILD_DIR + 'mathtmp'

staticpath = os.path.abspath(join(SPHINXDOC_PATH, '_static'))
latex_additional_macros = open(join(staticpath, 'mylatex-commands.sty'))

mathjax_latex_preamble = ""

LatexCommandTranslator = {}
LatexCommandTranslator['mathDictionary'] = {}
LatexCommandTranslator['commandDictionary'] = {}
LatexCommandTranslator['command1Dictionary'] = {}

trans = LatexCommandTranslator

for macro in latex_additional_macros:
    # used when building latex and pdf versions
    latex_elements['preamble'] += macro + '\n'
    # used when building html version
    pngmath_latex_preamble += macro + '\n'

    mathOperator = re.search('\\\\DeclareMathOperator{\\\\([A-Za-z]*)}{(.*)}',
                             macro)
    if mathOperator:
        LatexCommandTranslator['mathDictionary'][mathOperator.group(
            1)] = mathOperator.group(2).replace("\\", "\\\\")

    newCommand = re.search('\\\\newcommand{\\\\([A-Za-z]*)}{(.*)}', macro)
    if newCommand:
        LatexCommandTranslator['commandDictionary'][newCommand.group(
            1)] = newCommand.group(2).replace("\\", "\\\\")
    newCommand = re.search('\\\\renewcommand{\\\\([A-Za-z]*)}{(.*)}', macro)
    if newCommand:
        LatexCommandTranslator['commandDictionary'][newCommand.group(
            1)] = newCommand.group(2).replace("\\", "\\\\")

    newCommand = re.search('\\\\newcommand{\\\\([A-Za-z]*)}\\[1\\]{(.*)}',
                           macro)
    if newCommand:
        LatexCommandTranslator['command1Dictionary'][newCommand.group(
            1)] = newCommand.group(2).replace("\\", "\\\\")
    newCommand = re.search('\\\\renewcommand{\\\\([A-Za-z]*)}\\[1\\]{(.*)}',
                           macro)
    if newCommand:
        LatexCommandTranslator['command1Dictionary'][newCommand.group(
            1)] = newCommand.group(2).replace("\\", "\\\\")

latex_additional_macros.close()

plot2rst_commandTranslator = LatexCommandTranslator

# -- Options for manual page output -------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [('index', 'GIMLi', 'GIMLi Documentation', ['GIMLi Group'], 1)]

# If true, show URL addresses after external links.
# man_show_urls = False

# -- Options for Texinfo output -----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    ('index', 'GIMLi', 'GIMLi Documentation', 'GIMLi Group', 'GIMLi',
     'Geophysical Inversion and Modeling Library', 'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
# texinfo_appendices = []

# If false, no module index is generated.
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
texinfo_show_urls = 'footnote'

# -- Options for pybtex output ------------------------------------------------
# load our plugins for manual bibstyle


# temporary disable due to python3 pybtex quirks
for dist in pkg_resources.find_distributions(SPHINXDOC_PATH +
                                             "/_templates/pybtex_plugins/"):
    pkg_resources.working_set.add(dist)

# End pybtex stuff

# -- Options for doxylink -----------------------------------------------------
doxylink = {'gimliapi': (join(DOXY_BUILD_DIR, 'gimli.tag'), 'gimliapi')}

# Create small gallery of all tutorials and examples in the sidebar.
# from pygimli.misc.sidebar_gallery import make_gallery
sys.path.insert(0, os.path.abspath('.'))


make_gallery(SPHINXDOC_PATH, DOC_BUILD_DIR)
