# Dockerfile used to create a build environment for PyGimli based on the
# official Debian bookworm base image

# before proceeding, do the following:
#  * create an empty directory
#  * copy this file AND the build script, build_pygimli.sh, into this directory
#    and rename to "Dockerfile"
#  * run a 'chmod -R 0777 .' in the new directory. This is required so that the
#  container can copy the build results into this directory later

# Then, build the docker image by calling:
#    docker build -t "pg_build" .

# Afterwards, you can trigger the build in the container with:
#    docker run --rm -i -t -u gimli -v "${PWD}":/HOST -w /home/gimli "pg_build" /home/gimli/build_pygimli.sh

# Alternatively, you can spawn a shell in the container and build/modify manually:

#    docker run --rm -i -t -u gimli -v "${PWD}":/HOST -w /home/gimli "gimli/master" bash

# The build script can be found in /home/gimli/build_pygimli.sh

# Note that this command will mount the present directory to /HOST in the
# container, e.g., to copy the final build to the host computer
FROM debian:bookworm

RUN apt-get update

RUN apt-get install -y wget subversion git cmake mercurial
RUN apt-get install -y libboost-all-dev libblas-dev liblapack-dev
RUN apt-get install -y libsuitesparse-dev
RUN apt-get install -y libedit-dev clang llvm-dev python3-dev
RUN apt-get install -y python3 python3-numpy python3-matplotlib
RUN apt-get install -y python3-setuptools python3-venv
RUN apt-get install -y libopenblas-dev
RUN apt-get install -y tetgen
# required for building a Debian package
RUN apt-get install -y python3-stdeb dh-python

# not required, but used for debugging and testing
RUN apt-get install -y python3-pytest python3-pip

USER root
# set the root password to "root"
RUN sh -c "echo root:root |chpasswd"

RUN useradd gimli | chpasswd gimli
RUN mkdir /home/gimli
RUN chmod -R 0777 /home/gimli
RUN chown -R gimli:gimli /home/gimli

USER gimli
ENV HOME "/home/gimli"

# COPY build_pygimli.sh /home/gimli/build_pygimli.sh
COPY build_pygimli.sh /home/gimli/build_pygimli.sh
