# -*- coding: iso-8859-1 -*-

import wx

from pygimli.gui.base import AppResource

try:
    from pygimli.gui.wxmpl import AppResourceWxMPL
except Exception as e:
	print 'Import of wxmpl failed: ', e

from pygimli.gui.resources import loadIcon, MakeDisabledBitmap
from pygimli.importexport import reaGPX

HAVE_PROPGRID = False

class GPSViewerApp( AppResourceWxMPL ):
    ''
    ' Main Class for GPS Viewer App. Default render window is a wxmpl panel'
    ''
    def __init__( self, parent, rendererSlot, propertyInspectorSlot ):
        AppResourceWxMPL.__init__( self, parent, rendererSlot, propertyInspectorSlot )
        
        # set the name of this application that appears to the resource tree
        self.setName("GPS Viewer")
        
        ## optionaly load content informations for this application, generated by an gui-builder that wrote xrc-files
        ## eg. wxFormBuilder, __file__ is needed to find the xrc-file 
        self.loadXRC( 'gpsview.xrc', __file__ )
        
        ## register a menu to the main-MenuBar,
        ## using this function ensures that this menu will be shown/hiden respective to the activate status of the application
        self.mbCoordinatesMenu = self.createMainMenu( '&Coordinates' )
        
        ## create an item to the Coordinates menu
        self.createMenuItem( self.mbCoordinatesMenu
                                    , name = "Export ASCII"
                                    , help = 'auto'
                                    , function = self.exportAscii )
        ## create another item to the Coordinates menu
        self.createMenuItem( self.mbCoordinatesMenu
                                    , name = "Export UTM"
                                    , help = 'auto'
                                    , function = self.exportUTM )
                                    
        ## the application has some properties that can be altered by the property inspector (PI), loaded and saved
        #self.titleTextProp = self.appendProperty( "Title", default = 'unknown', valType = str )
                
        # do some stuff after this app has been created and registered to the resourceTree
        # the given method will be called when the app is in idle state
        # this ensures that all widgets has been created and shown before this method is called.
        self.parent.addCommandToOnIdleQueue( self.postCreate )


        # define local data after your needs
        self.gpsWPTs = None
    
    def postCreate( self ):
        # do nothing here in this application
        #self.createSubPanel( TestMPLApp, "wxMPL" )
        #self.createSubPanel( TestVTKApp, "wxVTK" )
        
    def createPropertyPanel( self, parent ):
        ''
        ' Define and return panel that is shown in the property-inspector (PI) '
        ' The panel will post created at the first call '
        ''

        # create a Notebook for the PI and add the content for the panel with the name piGPSViewerApp defined in gpsview.xrc
        panel = self.createPropertyInspectorNoteBookPanel( parent, 'piGPSViewerApp', title = 'GPS Viewer' )
            
        # define property behaviour
        #self.titleTextProp.setCtrl( ctrl = wx.xrc.XRCCTRL( panel,  'TitleTextCtrl' ) # name of the control in xrc
                                        #, ctrlEvent = wx.EVT_TEXT                        # the event that should observed
                                        #, targetFunct = self.setTitle )                  # the callback when the event is called
        
        return panel
        
    def openFile( self, files = None ):
        ''
        ' Load data here'
        ''
        self.gpsWPTs = readGPX( files )
        print self.gpsWPTs
    
    def exportUTM( self ):
        ''
        'Export coordinates in UTM format'
        ''
        pass

    def exportAscii( self ):
        ''
        'Export LonLat coordinates in ASCII format'
        ''
        pass